version: "3.7"

secrets:
  flask_key:
    file: ./tests/secrets/flask.key
  config_yml:
    file: ./tests/secrets/config-mock.yml

x-templates:
  api-server: &api-server
    build:
      context: .
      dockerfile: Dockerfile
    image: cyhy-api-server
    init: true
    restart: always
    environment:
      FLASK_ENV: development
    volumes:
      - ./src:/usr/src/src
      - ./tests/src:/home/cisa/tests
    ports:
      - "5000:5000"
    secrets:
      - source: config_yml
        target: config.yml
      - source: flask_key
        target: flask.key

services:
  bash:
    <<: *api-server
    entrypoint: /bin/sh

  test:
    <<: *api-server
    entrypoint: pytest -v
