version: "3.7"

secrets:
  flask_key_yml:
    file: ./secrets/flask_key.yml

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: cyhy-rest-server
    init: true
    ports:
      - "4443:5000"
    secrets:
      - source: flask_key_yml
