version: "3.7"

secrets:
  flask_key:
    file: ./tests/secrets/flask.key
  config_yml:
    file: ./tests/secrets/config-dev.yml

services:
  api-server: &api-server
    build:
      context: .
      dockerfile: Dockerfile
    image: cyhy-api-server
    init: true
    restart: always
    environment:
      FLASK_ENV: development
    volumes:
      - ./src:/usr/src/src
      - ./tests/src:/home/cisa/tests
    ports:
      - "5000:5000"
    secrets:
      - source: config_yml
        target: config.yml
      - source: flask_key
        target: flask.key

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./tests/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: -v

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  mail:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025
