version: "3.7"

secrets:
  flask_key:
    external: true
  config_yml:
    external: true

services:
  api-server:
    image: cyhy-api-server
    init: true
    restart: always
    environment:
      FLASK_ENV: production
    ports:
      - "5000:5000"
    secrets:
      - source: config_yml
        target: config.yml
      - source: flask_key
        target: flask.key
