version: "3.7"

secrets:
  flask_key:
    external: true
  cyhy_config_yml:
    external: true

services:
  api-server:
    image: cyhy-api-server
    init: true
    ports:
      - "4443:5000"
    secrets:
      - source: flask_key
      - source: cyhy_config_yml
