version: "3.7"

secrets:
  config_yml:
    file: ./tests/secrets/config.yml

x-templates:
  api-server: &api-server
    build:
      context: .
      dockerfile: Dockerfile
    image: cyhy-rest-server
    init: true
    volumes: # map for development only, comment out otherwise
     - ./src/cyhy_rest:/usr/src/cyhy_rest/cyhy_rest
     - ./tests/src:/home/cisa/tests
    ports:
      - "4443:5000"
    secrets:
      - source: config_yml

services:
  bash:
    <<: *api-server
    entrypoint: /bin/sh

  test:
    <<: *api-server
    entrypoint: pytest
